export let studentList=[
    "Rodoshi Raisa",
    "Raika Rhidita",
    "Mashiat Kabir Muskan",
    "Raiyan Binta Abdullah", 
    "Moin Ibna Mahmud",
    "Md. Nazmus Shakib",
    "Lammim Jerin Chowdhury",
    "Mahera Zaman",
    "Tasmin Zareen",
    "Sheikh Samia Afreen",
    "Jarin Tasnim Namisha", 
    "Raisa Ahmed",
    "S.Q.Redwanuzzaman",
    "MD SHAHRIAR FAIROJ", 
    "Ishra Chowdhury",
    "Md.Tanjil Kader Turag",
    "Tunaj Tajrin",
    "Zahir Uddin Mohammad Babar",
    "Showmik Jahan Shuvo",
    "Nayma Islam Sneha", 
   "Najifa Tabassum",
    "Abu Sayed",
    "Ariful Islam Akash",
    "Tandra Chakrabarty", 
    "Shafi Shahajad",
    "Maria Kibtia", 
    "Sadia Islam", 
    "Abida Islam",
    "Labiba Anjumi Kabir",
    "S.M.OMAR",
    "Tanvir Ahmed",
    "MD. Ifrat Zahan Chowdhury",
    "Shoumeeta Shotodol",
    "Fahad Alfi",
    "Asaduzzaman Khan Ratul",
    "Nishat Ramisa Islam",
    "Tahfima Mahmud", 
    "Nafiz Barsha",
    "Khadizatun Nur-E Sabrina",
    "Ashfikur Chowdhury",
    "Abdul Saki Toha", 
    "Jahidul Islam Mursalin",
    "HISHAM",
    "KHANDAKAR SHAJIA FARJANA SHUASHA",
    "Amir Hamza",
    "Arafat Ibna Zaman",
    "Arif Istiak Akanto",
    "Ayesha Meherin Himi",
    "Fahim Rifat",
    "Fahim Tanvir",
    "Faisal kadir",
    "Hasan Imam",
    "Jannatul Ferdousy",
    "MD MAHADI HASAN NUHASH",
    "Md. Nazmus Shakib",
    "Md.mahmudur rahamn",
    "Mt.Shamsunnahar Tisha", 
    "Namira Binte Haque",
    "Naomi Nitee Sarker",
    "Raffay Samdan",
    "Rahat Abedin",
    "Reeju Francis Leonard Gomes",
    "Samiul Hoque Sami",
    "SHAFIQUR RAHAMAN ALIN",
    "Soad Ahmed",
    "Sumaiya Rahman",
    "Ayesha Meherin Himi", 
    "Irteja haq",
    "Md. Tipu Sultan Lingkon",
    "Syed Mohat Masrur",
    "Sadman Saifee",
    "Rashad Mahmud", 
    "Murtaza Nafis Sadnan",
    "Sarwar Hossain Aman",
    "Farzana Chowdhury",
    "Sudipta Saha",
    "Fahima Ferdous",
    "Farhan Rahman",
    "Arpita Das",
    "Maimuna Akter Suchona",
    "Masrur Rahaman",
    "Sristy Roy",
    "Theophil Joy Dewri",
    "Tabassum Zahan",
    "Md .Mehedi Hussain Noyell",
    "Walid Bin Kamal",
    "MD. MASKUR ALI KHAN ANIK",
    "Shah Najifa Saiyara",
    "Sanzida Jarin Sonia",
    "Rasheduzzaman Antor",
    "Golam Muqtader Shaiq"
]
