export let studentList=[
    "Rodoshi Raisa",
    "Moin Ibna Mahmud",
    "Md. Nazmus Shakib",
    "Jarin Tasnim Namisha", 
    "S.Q.Redwanuzzaman",
    "Maimuna Akter Suchona",
    "Md.Tanjil Kader Turag",
    "Tunaj Tajrin",
   "Najifa Tabassum",
    "Abu Sayed",
    "Ariful Islam Akash",
    "Tandra Chakrabarty", 
    "Maria Kibtia", 
    "Sadia Islam", 
    "Abida Islam",
    "Tanvir Ahmed",
    "Shoumeeta Shotodol",
    "Nishat Ramisa Islam",
    "Tahfima Mahmud", 
    "Abdul Saki Toha", 
    "Arafat Ibna Zaman",
    "Arif Istiak Akanto",
    "Ayesha Meherin Himi",
    "Fahim Rifat",
    "Fahim Tanvir",
    "Hasan Imam",
    "MD MAHADI HASAN NUHASH",
    "Md. Nazmus Shakib",
    "Namira Binte Haque",
    "Reeju Francis Leonard Gomes",
    "Soad Ahmed",
    "Sumaiya Rahman",
    "Ayesha Meherin Himi", 
    "Sadman Saifee",
    "Murtaza Nafis Sadnan",
    "Farzana Chowdhury",
    "Sudipta Saha",
    "Fahima Ferdous",
    "Md .Mehedi Hussain Noyell",
    "Raika Rhidita",
    "Mashiat Kabir Muskan",
    "Raiyan Binta Abdullah", 
    "Lammim Jerin Chowdhury",
    "Mahera Zaman",
    "Tasmin Zareen",
    "Sheikh Samia Afreen", 
    "Raisa Ahmed",
    "MD SHAHRIAR FAIROJ", 
    "Ishra Chowdhury",
    "Zahir Uddin Mohammad Babar",
    "Showmik Jahan Shuvo",
    "Nayma Islam Sneha", 
    "Shafi Shahajad",
    "Labiba Anjumi Kabir",
    "S.M.OMAR",
    "MD. Ifrat Zahan Chowdhury",
    "Fahad Alfi",
    "Asaduzzaman Khan Ratul",
    "Nafiz Barsha",
    "Khadizatun Nur-E Sabrina",
    "Ashfikur Chowdhury",
    "Jahidul Islam Mursalin",
    "HISHAM",
    "KHANDAKAR SHAJIA FARJANA SHUASHA",
    "Amir Hamza",
    "Faisal kadir",
    "Jannatul Ferdousy",
    "Md.mahmudur rahamn",
    "Mt.Shamsunnahar Tisha", 
    "Naomi Nitee Sarker",
    "Raffay Samdan",
    "Rahat Abedin",
    "Samiul Hoque Sami",
    "SHAFIQUR RAHAMAN ALIN",
    "Irteja haq",
    "Md. Tipu Sultan Lingkon",
    "Syed Mohat Masrur",
    "Rashad Mahmud", 
    "Sarwar Hossain Aman",
    "Farhan Rahman",
    "Arpita Das",
    "Masrur Rahaman",
    "Sristy Roy",
    "Theophil Joy Dewri",
    "Tabassum Zahan",
    "Walid Bin Kamal",
    "MD. MASKUR ALI KHAN ANIK",
    "Shah Najifa Saiyara",
    "Sanzida Jarin Sonia",
    "Rasheduzzaman Antor",
    "Golam Muqtader Shaiq"
]
